apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - toto.com
  rules:
    - host: toto.com
      http:
        paths:
          - path: /
            backend:
              serviceName: hello-app
              servicePort: 80
